{
 "title": "Node Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(node_boot_time_seconds, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_boot_time_seconds{role=~\"$role\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Machine Specs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{role=\"$role\", instance=\"$instance\"}) / 60 / 60 / 24"
    }
   ]
  },
  {
   "title": "OS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{role=\"$role\", instance=\"$instance\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{role=\"$role\", instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{role=\"$role\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{role=\"$role\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Disk Size",
   "type": "singlestat",
   "description": "tmpfs, rootfs は除く",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max(node_filesystem_avail_bytes{instance=\"$instance\",role=\"$role\", device!~'tmpfs|rootfs'}) by (device))"
    }
   ]
  },
  {
   "title": "CPU Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "Load Average (1m)"
      },
      {
       "expr": "node_load5{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "Load Average (5m)"
      },
      {
       "expr": "node_load15{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "Load Average (15m)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Core 数で割っているので 100% になる",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\",role=\"$role\", mode!=\"idle\"}[5m])) by (mode)/3",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Process State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Processes" }
     ],
     "targets": [
      {
       "expr": "node_procs_running{role=\"$role\", instance=\"$instance\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "expr": "node_procs_blocked{role=\"$role\", instance=\"$instance\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_forks_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used RAM Memory",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"$instance\", role=\"$role\"} / node_memory_MemTotal_bytes{instance=\"$instance\", role=\"$role\"} * 100)"
      }
     ]
    },
    {
     "title": "Used Swap",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\",role=\"$role\"} - node_memory_SwapFree_bytes{instance=\"$instance\",role=\"$role\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance\",role=\"$role\"} )) * 100"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",role=\"$role\"} - node_memory_MemFree_bytes{instance=\"$instance\",role=\"$role\"} - (node_memory_Cached_bytes{instance=\"$instance\",role=\"$role\"} + node_memory_Buffers_bytes{instance=\"$instance\",role=\"$role\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$instance\",role=\"$role\"} + node_memory_Buffers_bytes{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",role=\"$role\"} - node_memory_SwapFree_bytes{instance=\"$instance\",role=\"$role\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "SUnreclaim（回収不可）"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "SReclaimable（回収可能）"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "description": "ページングは、プログラム全体でなく、ページ単位でメモリ領域を管理することです。\nスワップは、プログラム全体をディスクに退避してメモリに空きを作ることです。\n\nページアウトで解決できないくらいメモリ不足に陥っているようであれば、\nスワップアウトで使用可能領域を一気に空ける動きを想定します。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "tmpfs, rootfs は除く",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(100 - node_filesystem_free_bytes{instance=\"$instance\",role=\"$role\", device!~\"rootfs|tmpfs\"} / node_filesystem_size_bytes{instance=\"$instance\",role=\"$role\", device!~\"rootfs|tmpfs\"} * 100) by (device, mountpoint)",
       "legendFormat": "{{mountpoint}} [{{device}}]"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",role=\"$role\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "Read bytes [{{device}}]"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",role=\"$role\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "Write  bytes [{{device}}]"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "description": "ディスクが1秒当たりに処理できる I/O アクセスの数",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",role=\"$role\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "Reads completed [{{device}}]"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",role=\"$role\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "Writes completed [{{device}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic - Outbound",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Traffic - Inbound",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Traffic - Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Traffic - Drop",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$instance\",role=\"$role\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "TCP - Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{role=\"$role\", instance=\"$instance\"}",
       "legendFormat": "TCP connections - ESTABLISHED or CLOSE- WAIT"
      }
     ]
    },
    {
     "title": "TCP - TIME_WAIT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_tw{instance=\"$instance\",role=\"$role\"}",
       "legendFormat": "TIME_WAIT"
      }
     ]
    }
   ]
  }
 ]
}